### ISSUE TITLE
Menu items invisible when using nc_money app

### ISSUE THREAD

**Issue by meichthys** [powerpaul17/nc_money#11]
When using the nc_money app, the main Nextcloud menu items seem to be invisible:
![image](https://user-images.githubusercontent.com/10717998/195995702-9e5e1e27-f3e5-425c-b6bf-e27c3d16359f.png)

For reference, i'm running NC25RC3 in case that matters.

**Comment by powerpaul17** [comment]
Yes, I also noticed that in NC25, haven't figured out why yet, but it can also be a problem on their side. The custom background is also not updating correctly for some apps on my instance.. Dark mode is also broken in NC25 since it's not using the `theme--dark` class on the body anymore. I'll try and address these issues to make the app compatible with NC25.

**Comment by powerpaul17** [comment]
fixed in e452a97f89f6c0cd433bb3135dbc6b1155dda8b1
