### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by horald** [powerpaul17/nc_money#2]
How can I install the app. I have copied the source to the apps directory but I can't see a new app. Thanks in advance.

**Comment by powerpaul17** [comment]
Hello! First I have to tell you that I don't consider the app stable. That's the reason I haven't released it yet. There are still some ugly style/design issues I have to resolve.

Secondly, have you checked the permissions of the files? Otherwise you may have to look up in the nextcloud documentation.

**Comment by powerpaul17** [comment]
I think logging out and back in also might help. Then you should be able to enable the app.

**Comment by horald** [comment]
Hello, sorry I can't activate money. If I try, I get the error:
>>Could not download app money<<
But the app money is on the server! What's wrong? Thanks.

**Comment by powerpaul17** [comment]
Have you cloned the git repository into your apps folder and made sure the name of the folder is "money"?

**Comment by horald** [comment]
ok, the folder name was the problem. Now I can see the app "money". How can I add an account. If I click at "Assets" and afterwards to "+ Add account" nothing happens. Thanks for your help.

**Comment by powerpaul17** [comment]
It was a small bug, I just fixed it in the latest commit. Thanks for pointing out. Just want to tell you once again, that while the basic functionality is working, it is still work in progress.
