### ISSUE TITLE
No Add Account In nextcloud AIO

### ISSUE THREAD

**Issue by megvadulthangya** [powerpaul17/nc_money#38]
Hi! Any suggestion why i dont see the Add Account option? 

Im on Nextcloud AIO/Nextcloud 24.0.8

Maybe something blocking this thing? 

I using nginx Proxy manager.... so reverse proxy...

**Comment by powerpaul17** [comment]
Hello, a first guess would be a bug fixed but it is only available on NC 25 since I decided to target NC 25 due to breaking changes for app development.

**Comment by R7JANV1** [comment]
I have the same problem with AIO under stable (Nextcloud 25.0.3)

**Comment by powerpaul17** [comment]
Can you please provide any logs (browser or server). I don't know the full architecture of AIO but I don't think there should be any differences regarding the functionality of the app..

**Comment by R7JANV1** [comment]
Zugriff verboten
CSRF check failed

Server Logs: none

**Comment by powerpaul17** [comment]
Ok, just to be clear: you can select the option for creating the account but you get the error from the request?

**Comment by R7JANV1** [comment]
the button (if there is one at all, I've never seen it but it would be hotly debated, so I assume there should be one) where accounts are created is not displayed to me, but when I call up the URL of the button I get it  the mentioned error.

**Comment by powerpaul17** [comment]
Just to be clear, there is no "button", you have to hover over the account type and then there should be a "+"-Sign:
![image](https://user-images.githubusercontent.com/2046162/222724788-8290ebd6-8be9-4952-9190-0f94d6e76cf0.png)

This should create a new account for the account type. I can't of a possibility that it would not be there in AIO since the frontend should be the same.

If you encounter any issues when actually trying to add an account there has to be an error message in the browser console, even if it is just a failed network request. Failed network requests normally have the error as the response.

**Comment by R7JANV1** [comment]
Okay then everything works as it should, sorry we have talked completely past each other. But what has it to do with the mentioned URL? /accounts?

**Comment by powerpaul17** [comment]
@megvadulthangya Is this fixed for you now? Did you find the button?

**Comment by powerpaul17** [comment]
@R7JANV1 I think you refer to #29, right? Please continue discussion there.

**Comment by megvadulthangya** [comment]
> @megvadulthangya Is this fixed for you now? Did you find the button?

What would fix this? What you talk about? 
Money on my nextcloud instance is completely unuseful...

**Comment by powerpaul17** [comment]
> Just to be clear, there is no "button", you have to hover over the account type and then there should be a "+"-Sign: ![image](https://user-images.githubusercontent.com/2046162/222724788-8290ebd6-8be9-4952-9190-0f94d6e76cf0.png)
> 
> This should create a new account for the account type. I can't think of any possibility that it would not be there in AIO since the frontend should be the same.
> 
> If you encounter any issues when actually trying to add an account there has to be an error message in the browser console, even if it is just a failed network request. Failed network requests normally have the error as the response.

The screenshot I posted shows where you can find the button to add an account. I assumed you read the answers to the ticket you opened.

**Comment by megvadulthangya** [comment]
**Im currently renovating a house, and it's hard for me to pay attention to several things...** 
Sorry for not responding ....

I read all the msg's... but don't find it... O.o 
[Video](https://youtu.be/Ys2DhGTz8LA)

Im on Nextcloud AIO which is 24.x something version... 


_Maybe this is a stupid question, but maybe you know the answer better then me_
If i try to install [this ](https://hub.docker.com/_/nextcloud) nextcloud docker ... fpm-alpine whic is installing nextcloud 26 as i see on that page... Do i still have talk function on nextcloud? Or thats an AIO only feature, or i need to install from Apps, after nextcloud is up?

Or i can update somehow the 24.x version nextcloud AIO to nextcloud 25x or 26x without loosing files? 
Last week i find some time to google it and try to update to 25 but without success... plus after that when i restart my oracle cloud instance where docker and nextcloud AIO is installed nextcloud AIO failed to start automatically... => I guess later, when i find time this, i will remove this nextcloud AIO installation from Docker, delete all and install the latest nextcloud, i dont know yet...

**Comment by powerpaul17** [comment]
Ok, don't worry, I also have a lot to do in my life.. :wink: I was just surprised because of your answer and I want to get issues sorted out eventually. In the video you made there is the +-Button visible on hover, just as in the screenshot. This is the "button" to create a new account in the category.

Regarding your AIO questions, I cannot help you with that since I don't know exactly how that works, there should be documentation elsewhere.
